name:                deadmanswitch
version:             0.1.0.0
synopsis:            execute an action at program exit, no matter what.
homepage:            https://github.com/mwotton/deadmanswitch#readme
license:             BSD3
author:              Mark Wotton
maintainer:          mwotton@gmail.com
copyright:           2018 Mark Wotton
category:            Control
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - async
  - extra
  - unix

library:
  source-dirs:      src
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - hspec
    - deadmanswitch
    - temporary
    - directory
    - unix
